### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement github (from versions: none)

### ISSUE THREAD

**Issue by woosal1337** [brpaz/ulauncher-github#15]
GitHub Library installation on Python.

While it is suggesting in the app to have the library as following in order to proceed to work:
`pip3 install github`

such library does not exist. Did you mean:
`pip3 install pygithub`

**Comment by elpupi** [comment]
I read the source code. Indeed, the dependency is ```pygithub```. It is written in the [README.md](https://github.com/brpaz/ulauncher-github/blob/master/README.md) and also you find it in the file [requirements.txt](https://github.com/brpaz/ulauncher-github/blob/master/requirements.txt)

**Comment by woosal1337** [comment]
It might be on the files you have mentioned, however, it was not really `pygithub` on the Ulauncher itself. Through Ulauncher, regular `github` was required to be installed was mentioned.

**Comment by elpupi** [comment]
Yes you are right
