### ISSUE TITLE
[Bug]: Error on installing dependencies

### ISSUE THREAD

**Issue by hrqmonteiro** [brpaz/ulauncher-github#20]
### Description?

```
[hrq@fedora ~]$ pip install -r https://github.com/brpaz/ulauncher-github/blob/master/requirements.txt
Defaulting to user installation because normal site-packages is not writeable
WARNING: Cache entry deserialization failed, entry ignored
ERROR: Invalid requirement: '<!DOCTYPE html>' (from line 8 of https://github.com/brpaz/ul
```

### Extension Logs

```shell
None
```

**Comment by julianhille** [comment]
have a look at: #21 
or try this: `pip install -r https://raw.githubusercontent.com/brpaz/ulauncher-github/master/requirements.txt`

**Comment by hrqmonteiro** [comment]
> have a look at: #21 or try this: `pip install -r https://raw.githubusercontent.com/brpaz/ulauncher-github/master/requirements.txt`

Now it gives me another error:

![Screenshot from 2022-09-28 09-01-06](https://user-images.githubusercontent.com/17055027/192773673-74a22ca8-6d24-4ef0-9bd6-0421911aa61c.png)

```
pip install -r https://raw.githubusercontent.com/brpaz/ulauncher-github/master/requirements.txt
Defaulting to user installation because normal site-packages is not writeable
ERROR: Invalid requirement: 'pygithub=~1.55' (from line 1 of https://raw.githubusercontent.com/brpaz/ulauncher-github/master/requirements.txt)
```

**Comment by julianhille** [comment]
Sorry did not check if that works, i'm not using this module nor maintain it, i'm just a passerby :P. The requirement format/syntax is invalid here.

short solution which should work for you:

```
pip install pygithub=~1.55.0 requests
```

**Comment by julianhille** [comment]
for the sake of completeness here is the other fix as a PR: https://github.com/brpaz/ulauncher-github/pull/22
