### ISSUE TITLE
Unexpected API error. KeyError: com.github.brpaz.ulauncher-github

### ISSUE THREAD

**Issue by zeddo123** [brpaz/ulauncher-github#3]
Hi,
I have this issue when trying to install the extension.
-I have installed PyGithub.
![image](https://user-images.githubusercontent.com/34837535/53681538-7e922980-3ceb-11e9-8db7-b89c3745fc28.png)
![image](https://user-images.githubusercontent.com/34837535/53681573-cadd6980-3ceb-11e9-983a-05651e2234bd.png)

**Comment by Hergeirs** [comment]
You probably should blur out your access token.

**Comment by nickpwhite** [comment]
I experienced the same issue.

I was able to fix it by first installing `pygithub` `pip install --user pygithub` and then by removing the extension and readding it. I also regenerated a new access key, but I don't think that was related to the fix.

**Comment by brpaz** [comment]
This kind of issue is usually related to missing dependencies. doing what @nickpwhite did should work. 
I will close this issue. Feel free to re-open it if needed.

Thank you.
